### ISSUE TITLE
Group stickers on map when zoomed out

### ISSUE THREAD

**Issue by nickygerritsen** [GEPWNAGE/GESTICKER#16]
If you are zoomed out we still show all stickers on the map, which will never work. We should do something like group them and show the number of stickers, and when clicking on them show a list of them.

**Comment by Mesoptier** [comment]
Split this into two issues, see #18 🙂

**Comment by Mesoptier** [comment]
As for this issue; at higher zoom levels clicking on a "bundled" marker should zoom in on it. When on the lowest zoom level it should show a list or something.

**Comment by Mesoptier** [comment]
Fixed on develop.

![image](https://user-images.githubusercontent.com/322632/63229886-7714fd00-c205-11e9-84c2-da9ef24dc3d1.png)
