### ISSUE TITLE
Come up with a backronym for GESTICKER

### ISSUE THREAD

**Issue by Mesoptier** [GEPWNAGE/GESTICKER#4]
https://en.wikipedia.org/wiki/Backronym

**Comment by sqlr** [comment]
GEWIS Sticker Tracker: Inventarisatie van Coordinaten, Kwantiteit, Elevaties en Rariteit

**Comment by sqlr** [comment]
GEWIS Expedieert Stickers, Internationaal, Creatief, Kunstzinnig En Roekeloos

**Comment by Mesoptier** [comment]
Ik heb voor "GEWIS Sticker Tracker: Inventarisatie van Coordinaten, Kwantiteit, Elevaties en Rariteit" gekozen. Erg leuk bedacht, @wmouwen! Ik heb het als `title` toegevoegd op "GESTICKER" in de header.
